version: '3'

services:

  artifact-service:
    image: mdeforge/artifact-service
    container_name: artifact-service
    ports:
      - 5005:8080
    links:
      - mysql
      - kafka
      - zookeeper
      - cdcservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      SPRING_DATASOURCE_TIMEOUT: 10000
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      MONGODB: mongodb:27017/artifactdb

  project-service:
    image: mdeforge/project-service
    container_name: project-service
    ports:
      - 5004:8080
    links:
      - mysql
      - kafka
      - zookeeper
      - cdcservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      SPRING_DATASOURCE_TIMEOUT: 10000
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      MONGODB: mongodb:27017/projectdb

  user-service:
    image: mdeforge/user-service
    container_name: user-service
    ports:
      - 5003:8080
    links:
      - mysql
      - kafka
      - zookeeper
      - cdcservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      SPRING_DATASOURCE_TIMEOUT: 10000
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      MONGODB: mongodb:27017/userdb

  workspace-service:
    image: mdeforge/workspace-service
    container_name: workspace-service
    ports:
      - 5002:8080
    links:
      - mysql
      - kafka
      - zookeeper
      - cdcservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      SPRING_DATASOURCE_TIMEOUT: 10000
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      MONGODB: mongodb:27017/workspacedb

  mdeforge-view-service:
    image: mdeforge/mdeforge-view-service
    container_name: mdeforge-view-service
    ports:
      - 5001:8080
    links:
      - mysql
      - kafka
      - zookeeper
      - cdcservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      SPRING_DATASOURCE_TIMEOUT: 10000
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      MONGODB: mongodb:27017/mdeforgedb

  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.14.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: eventuateio/eventuateio-local-kafka:0.14.0
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  mysql:
    image: eventuateio/eventuate-tram-sagas-mysql:0.3.0.RELEASE
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  cdcservice:
    image: eventuateio/eventuate-tram-cdc-mysql-service:0.3.0.RELEASE
    ports:
      - "8099:8080"
    links:
      - mysql
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890

  mongodb:
    image: mongo:3.0.15
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
